version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  store_results:
    steps:
      - store_test_results:
          path: /tmp/test-results
workflows:
  e2e-test:
    jobs:
      - node/test:
          version: lts
      - store_results

